language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - gulp build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $h
  local_dir: build
  target_branch: master
  on:
    branch: source